
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: postgres
  password: moise@1990
  host: 127.0.0.1
  port: 5432

development:
  <<: *default
  database: itan_audiobook_backend_development


test:
  <<: *default
  database: itan_audiobook_backend_test


production:
  <<: *default
  database: itan_audiobook_backend_production
  username: postgres
  password: <%= ENV["APP_PASSWORD"] %>
  url: <%= ENV['DATABASE_URL'] %>